spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patient_service?createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
    
qr:
  storage:
    path: ./qr-codes/
